### ISSUE TITLE
XYZ parser fails with the comment line empty

### ISSUE THREAD

**Issue by FabianGD** [sheepforce/Spicy#14] opened 2019-09-19 12:53 UTC
I noticed that the current .xyz-parser (parseXYZ) fails to parse the molecule,  as long as there is nothing on the second line (usually used for comments).

I suppose this should not crash in the first place?
As a first measure, I added a water molecule to the goldentest folder (H2O_broken.xyz) for testing this.

**Comment by sheepforce** [comment] 2019-09-19 12:58
You are correct. The issue is, that the parser skips whitespace after the number of atoms and then expects one line of comment. This means if the comment is empty, the first atom line will be used as comment and only n - 1 atoms can be found then, see these lines:

      nAtoms <- skipSpace' *> decimal
      label  <- skipSpace *> takeWhile (not . isEndOfLine) <* skipSpace
      atoms <- count nAtoms xyzLineParser

The issue is the mindless `skipSpace` in line 2. I will fix this.

**Comment by FabianGD** [comment] 2019-09-19 12:59
K. I added a goldentests test case for this in the InternalCoords branch.

**Comment by sheepforce** [comment] 2019-09-23 21:36
Fixed by #15.

**Closed as completed by sheepforce** 2019-09-23 21:36 UTC
Labels: bug
